# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'image_recognation.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from guizero import App
from guizero import App, Text,TextBox,PushButton 
from skimage.transform import resize
import matplotlib.pyplot as plt
import pandas as pd
import tensorflow as tf
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense,Flatten,Conv2D,MaxPooling2D,Dropout
from tensorflow.keras import layers
from keras.utils import to_categorical
import numpy as np
plt.style.use('fivethirtyeight')
from keras.datasets import cifar10
(x_train,y_train),(x_test,y_test)=cifar10.load_data()
classification=['ariplane','automobile','bird','cat','deer','dog','frog','horse','ship','truck']
y_train_one_hot=to_categorical(y_train)
y_test_one_hot=to_categorical(y_test)
x_train=x_train/255
x_test=x_test/255
model=Sequential()
model.add(Conv2D(32,(5,5),activation='relu',input_shape=(32,32,3)))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Conv2D(32,(5,5),activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Flatten())
model.add(Dense(1000,activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(500,activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(250,activation='relu'))
model.add(Dense(10,activation='softmax'))
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
hist=model.fit(x_train,y_train_one_hot,batch_size=256,epochs=10,validation_split=0.2)

class Ui_input(object):
    def setupUi(self, input):
        input.setObjectName("input")
        input.resize(791, 593)
        input.setStyleSheet("background-color: rgb(242, 207, 255);")
        self.centralwidget = QtWidgets.QWidget(input)
        self.centralwidget.setObjectName("centralwidget")
        self.display_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.display_2.setGeometry(QtCore.QRect(0, -10, 791, 561))
        self.display_2.setStyleSheet("background-image: url(:/newPrefix/0s1B2u.jpg);")
        self.display_2.setObjectName("display_2")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_2.setGeometry(QtCore.QRect(364, 0, 431, 551))
        self.tabWidget_2.setStyleSheet("border: 0px; background-color:rgba(0,0,0,0%)")
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.display_3 = QtWidgets.QTextBrowser(self.tab_3)
        self.display_3.setGeometry(QtCore.QRect(0, -10, 431, 541))
        self.display_3.setStyleSheet("background-color: rgb(247, 123, 123);")
        self.display_3.setObjectName("display_3")
        self.yes = QtWidgets.QPushButton(self.tab_3)
        self.yes.setGeometry(QtCore.QRect(30, 210, 171, 81))
        self.yes.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(60, 188, 0);\n"
"border-radius:40px;")
        self.yes.setObjectName("yes")
        self.display = QtWidgets.QTextBrowser(self.tab_3)
        self.display.setGeometry(QtCore.QRect(50, 320, 341, 141))
        self.display.setStyleSheet("border-radius:10px;\n"
"font: 20pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(239, 239, 239);")
        self.display.setObjectName("display")
        self.no = QtWidgets.QPushButton(self.tab_3)
        self.no.setGeometry(QtCore.QRect(230, 210, 171, 81))
        self.no.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"border-radius:40px;\n"
"background-color: rgb(255, 0, 0);")
        self.no.setObjectName("no")
        self.label_4 = QtWidgets.QLabel(self.tab_3)
        self.label_4.setGeometry(QtCore.QRect(90, 120, 241, 71))
        self.label_4.setStyleSheet("font: 75 20pt \"MS Shell Dlg 2\";\n"
"border: 0px; background-color:rgba(0,0,0,0%);\n"
"color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.tabWidget_2.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.display_4 = QtWidgets.QTextBrowser(self.tab_4)
        self.display_4.setGeometry(QtCore.QRect(0, 0, 431, 541))
        self.display_4.setStyleSheet("background-color: rgb(241, 127, 64);")
        self.display_4.setObjectName("display_4")
        self.label_5 = QtWidgets.QLabel(self.tab_4)
        self.label_5.setGeometry(QtCore.QRect(0, 50, 421, 71))
        self.label_5.setStyleSheet("font: 75 20pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(241, 127, 64);\n"
"color: rgb(255, 255, 255);\n"
"border: 0px; background-color:rgba(0,0,0,0%)")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.tab_4)
        self.label_6.setGeometry(QtCore.QRect(60, 440, 341, 71))
        self.label_6.setStyleSheet("font: 75 15pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"border: 0px; background-color:rgba(0,0,0,0%)")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.tab_4)
        self.label_7.setGeometry(QtCore.QRect(0, 110, 421, 71))
        self.label_7.setStyleSheet("font: 75 20pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"border: 0px; background-color:rgba(0,0,0,0%)")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.tab_4)
        self.label_8.setGeometry(QtCore.QRect(40, 380, 161, 71))
        self.label_8.setStyleSheet("font: 75 20pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"border: 0px; background-color:rgba(0,0,0,0%)")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.tab_4)
        self.label_9.setGeometry(QtCore.QRect(0, 0, 421, 71))
        self.label_9.setStyleSheet("font: 75 20pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"border: 0px; background-color:rgba(0,0,0,0%)")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.tab_4)
        self.label_10.setGeometry(QtCore.QRect(0, 170, 421, 71))
        self.label_10.setStyleSheet("font: 75 20pt \"MS Shell Dlg 2\";\n"
"border: 0px; background-color:rgba(0,0,0,0%);\n"
"color: rgb(255, 255, 255);")
        self.label_10.setObjectName("label_10")
        self.tabWidget_2.addTab(self.tab_4, "")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 510, 241, 41))
        self.label.setStyleSheet("border: 0px; background-color:rgba(0,0,0,0%)")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(90, 0, 241, 71))
        self.label_2.setStyleSheet("font: 75 20pt \"MS Shell Dlg 2\";\n"
"border: 0px; background-color:rgba(0,0,0,0%)")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 50, 351, 81))
        self.label_3.setStyleSheet("font: 25pt \"MS Shell Dlg 2\";\n"
"border: 0px; background-color:rgba(0,0,0,0%)")
        self.label_3.setObjectName("label_3")
        input.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(input)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 791, 26))
        self.menubar.setObjectName("menubar")
        input.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(input)
        self.statusbar.setObjectName("statusbar")
        input.setStatusBar(self.statusbar)

        self.retranslateUi(input)
        self.tabWidget_2.setCurrentIndex(0)
        self.yes.clicked.connect(self.started)
        self.no.clicked.connect(self.stoped)
        QtCore.QMetaObject.connectSlotsByName(input)

    def started(self):
        new_image=plt.imread('myfile.jpg')
        re_image=resize(new_image, (32,32,3))
        predictions=model.predict(np.array([re_image]))
        list_index=[0,1,2,3,4,5,6,7,8,9]
        x=predictions
        for i in range(10):
            for j in range(10):
                if x[0][list_index[i]] > x[0][list_index[j]]:
                    temp=list_index[i]
                    list_index[i]=list_index[j]
                    list_index[j]=temp  
        real=classification[list_index[0]]  
        self.display.append(real)    

    def stoped(self):
            self.display.append('Open the help tab')      

    def retranslateUi(self, input):
        _translate = QtCore.QCoreApplication.translate
        input.setWindowTitle(_translate("input", "MainWindow"))
        self.yes.setText(_translate("input", "Yes"))
        self.no.setText(_translate("input", "No"))
        self.label_4.setText(_translate("input", "Are you ready?"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("input", "Start"))
        self.label_5.setText(_translate("input", "2.Image format:jpg"))
        self.label_6.setText(_translate("input", "seyedamirshobeiri@gmail.com"))
        self.label_7.setText(_translate("input", "3.Image name:myfile"))
        self.label_8.setText(_translate("input", "Contact us:"))
        self.label_9.setText(_translate("input", "1.add image to the path app"))
        self.label_10.setText(_translate("input", "4.sample->myfile.jpg"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("input", "Help"))
        self.label.setText(_translate("input", "CRAFTED BY @SEYEDAMIR SHOBEIRI"))
        self.label_2.setText(_translate("input", "welcome to"))
        self.label_3.setText(_translate("input", "Image recognation"))
import image1


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    input = QtWidgets.QMainWindow()
    ui = Ui_input()
    ui.setupUi(input)
    input.show()
    sys.exit(app.exec_())
